Repository w3c/vc-di-eddsa, pull requests merged in 2024-06, with the labels that each got.

#79 JCS Context Injection
  index.html
Labels: normative, CR1

#80 Update JCS Test Vectors
  TestVectors/eddsa-jcs-2022/combinedHashJCS.txt
  TestVectors/eddsa-jcs-2022/proofCanonJCS.txt
  TestVectors/eddsa-jcs-2022/proofConfigJCS.json
  TestVectors/eddsa-jcs-2022/proofHashJCS.txt
  TestVectors/eddsa-jcs-2022/sigBTC58JCS.txt
  TestVectors/eddsa-jcs-2022/sigHexJCS.txt
  TestVectors/eddsa-jcs-2022/signedJCS.json
Labels: editorial, CR1

#83 Changed the RDF Canon references to the official one
  index.html
Labels: editorial

#84 Unify error codes and error handling language
  index.html
Labels: normative, CR1

#85 Updated context in examples 2 and 6.
  index.html
Labels: editorial, CR1
